spring:
  datasource:
    url: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_NAME}.rns3u.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jpa:
    open-in-view: false
    hibernate:
    ddl-auto: validate

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}