spring:
  datasource:
    url: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@$Cluster0.rns3u.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jpa:
    open-in-view: false
    hibernate:
    ddl-auto: validate

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}