spring:
  data:
    mongodb:
    url: ${SPRING_DATA_MONGODB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jpa:
    open-in-view: false
    hibernate:
    ddl-auto: validate

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}