spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  rabbitmq:
     host: ${RABBITMQ_HOST}
     port: ${RABBITMQ_PORT}
     username: ${RABBITMQ_USERNAME}
     password: ${RABBITMQ_PASSWORD}